before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: "owncast"
    env:
      - CGO_ENABLED=1
    binary: owncast
    flags:
      - -trimpath
    ldflags: 
      - -s -w 
      - -X main.BuildVersion={{ .Version }} 
      - -X main.GitCommit={{ .Commit }}
      - -X main.BuildType={{ .Os }}-{{ .Arch }}
      - -X main.Date={{ .CommitDate }}
    goos:
      - linux
    goarch:
      - amd64
      - 386
    # - arm
    goarm:
    # - 7
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: GitHub-Zip
    builds:
      - owncast
    format: zip
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      386: 32bit
      amd64: 64bit
      darwin: macOS
      linux: linux

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
