before:
  hooks:
    - rm -rf ./webroot/hls/* ./hls/* ./webroot/thumbnail.jpg ./build/javascript/node_modules
    - go mod tidy
    - go mod download
    - build/javascript/tailwind.sh
    - build/admin/bundleAdmin.sh

builds:
  - id: "owncast"
    env:
      - CGO_ENABLED=1
    binary: owncast
    flags:
      - -trimpath
    ldflags: 
      - -s -w 
      - -X main.BuildVersion={{ .Version }} 
      - -X main.GitCommit={{ .Commit }}
      - -X main.BuildType={{ .Os }}-{{ .Arch }}
      - -X main.Date={{ .CommitDate }}
    goos:
      - linux
    goarch:
      - amd64
      - 386
    # - arm
    goarm:
    # - 7
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - cmd: mkdir -p dist/{{ .ProjectName }}_{{ .Target }}/data
        - cmd: cp -R webroot dist/{{ .ProjectName }}_{{ .Target }}/
        - cmd: cp -R static dist/{{ .ProjectName }}_{{ .Target }}/
        - cmd: cp build/javascript/tailwind.min.css dist/{{ .ProjectName }}_{{ .Target }}/webroot/js/web_modules/tailwindcss/dist/tailwind.min.css
        - cmd: cp LICENSE README.md dist/{{ .ProjectName }}_{{ .Target }}/

archives:
  - id: GitHub-Zip
    builds:
      - owncast
    format: zip
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      386: 32bit
      amd64: 64bit
      darwin: macOS
      linux: linux
    files:
      - README.md
      - LICENSE
      - webroot/*/**
      - static/*/**
      - data

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
