name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: sudo apt-get update -qq && sudo apt-get install gcc-multilib libc6-dev-i386-cross npm

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install Go Pkger
        run: go get github.com/markbates/pkger/cmd/pkger

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --skip-publish --skip-sign --rm-dist
